title: "SOCC Research Group"
description: "Service-Oriented, Cloud and Fog Computing Research Group at the University of Pisa."
url: "https://di-unipi-socc.github.io"
baseurl: "/"
markdown: kramdown
pub_source: bib
pub_json: /assets/publications.json
exclude:
  - package.json
  - package-lock.json
  - node_modules/
  - Makefile
  - README.md
  - LICENSE.md
